In [52]:
import pandas as pd

In [53]:
df = pd.read_csv("coffee_shop_sample.csv")
print(df.columns)

Index(['transaction_date', 'transaction_time', 'customer_id', 'quantity',
       'line_item_amount', 'unit_price', 'product_group', 'product_category',
       'product_type', 'current_wholesale_price', 'customer_since',
       'customer_birth_year', 'customer_generation'],
      dtype='object')

In [54]:
df

,transaction_date,transaction_time,customer_id,quantity,line_item_amount,unit_price,product_group,product_category,product_type,current_wholesale_price,customer_since,customer_birth_year,customer_generation
0,2019-04-18,06:33:22,NaN,1,2.50,2.50,Beverages,Tea,Brewed herbal tea,0.63,NaN,NaN,NaN
1,2019-04-13,07:17:16,5655.0,1,3.00,3.00,Beverages,Tea,Brewed Black tea,0.75,2018-06-15,1993.0,Younger Millennials
2,2019-04-06,16:27:42,599.0,1,2.50,2.50,Beverages,Tea,Brewed Chai tea,0.63,2018-09-12,1988.0,Older Millennials
3,2019-04-17,06:47:08,5572.0,2,6.00,3.00,Beverages,Tea,Brewed herbal tea,0.75,2017-04-06,1956.0,Baby Boomers
4,2019-04-06,17:33:47,5555.0,2,7.00,3.50,Beverages,Coffee,Organic brewed coffee,0.70,2019-03-19,1999.0,Gen Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-04-09,19:58:13,642.0,1,3.75,3.75,Beverages,Drinking Chocolate,Hot chocolate,2.81,2018-12-10,1993.0,Younger Millennials
96,2019-04-09,08:08:00,NaN,1,4.38,4.38,Food,Bakery,Pastry,2.11,NaN,NaN,NaN
97,2019-04-25,16:59:43,5119.0,1,2.65,2.65,Food,Bakery,Scone,2.11,2017-03-31,1982.0,Older Millennials
98,2019-04-18,11:11:26,NaN,2,5.00,2.50,Beverages,Tea,Brewed herbal tea,0.63,NaN,NaN,NaN
99,2019-04-22,18:05:59,513.0,1,2.20,2.20,Beverages,Coffee,Organic brewed coffee,0.44,2018-03-18,1977.0,Gen X

In [55]:
# some of the rows had NA values in the Customer birth year column

df_dropna = df.dropna()

In [56]:
df_dropna

,transaction_date,transaction_time,customer_id,quantity,line_item_amount,unit_price,product_group,product_category,product_type,current_wholesale_price,customer_since,customer_birth_year,customer_generation
1,2019-04-13,07:17:16,5655.0,1,3.00,3.00,Beverages,Tea,Brewed Black tea,0.75,2018-06-15,1993.0,Younger Millennials
2,2019-04-06,16:27:42,599.0,1,2.50,2.50,Beverages,Tea,Brewed Chai tea,0.63,2018-09-12,1988.0,Older Millennials
3,2019-04-17,06:47:08,5572.0,2,6.00,3.00,Beverages,Tea,Brewed herbal tea,0.75,2017-04-06,1956.0,Baby Boomers
4,2019-04-06,17:33:47,5555.0,2,7.00,3.50,Beverages,Coffee,Organic brewed coffee,0.70,2019-03-19,1999.0,Gen Z
6,2019-04-10,07:09:32,8121.0,1,3.00,3.00,Beverages,Tea,Brewed herbal tea,0.75,2018-03-25,1996.0,Gen Z
10,2019-04-01,15:54:39,781.0,2,7.00,3.50,Beverages,Coffee,Organic brewed coffee,0.70,2018-11-02,1991.0,Younger Millennials
14,2019-04-02,17:02:59,5754.0,1,3.00,3.00,Food,Bakery,Scone,1.95,2018-02-01,1990.0,Younger Millennials
15,2019-04-20,10:47:59,5667.0,1,3.25,3.25,Food,Bakery,Scone,2.11,2017-04-28,1983.0,Older Millennials
16,2019-04-05,10:44:39,5736.0,2,6.20,3.10,Beverages,Coffee,Premium brewed coffee,0.62,2017-01-04,1980.0,Older Millennials
17,2019-04-07,12:12:14,188.0,2,6.00,3.00,Beverages,Coffee,Drip coffee,0.60,2018-06-04,1982.0,Older Millennials
21,2019-04-05,10:27:45,8372.0,2,8.50,4.25,Beverages,Coffee,Barista Espresso,0.85,2017-01-21,1997.0,Gen Z
23,2019-04-06,18:09:01,5872.0,2,9.00,4.50,Beverages,Drinking Chocolate,Hot chocolate,3.38,2018-03-12,1977.0,Gen X
30,2019-04-02,18:50:47,8447.0,2,6.00,3.00,Beverages,Coffee,Gourmet brewed coffee,0.60,2017-05-06,2000.0,Gen Z
32,2019-04-06,18:09:21,8378.0,1,3.00,3.00,Beverages,Coffee,Drip coffee,0.60,2017-04-16,1998.0,Gen Z
35,2019-04-05,15:48:19,116.0,1,3.10,3.10,Beverages,Tea,Brewed Chai tea,0.78,2017-11-17,1969.0,Gen X
37,2019-04-02,17:11:47,19.0,2,9.50,4.75,Beverages,Drinking Chocolate,Hot chocolate,3.56,2017-02-23,1953.0,Baby Boomers
39,2019-04-27,10:20:21,8478.0,1,4.75,4.75,Beverages,Drinking Chocolate,Hot chocolate,3.56,2017-07-30,1971.0,Gen X
42,2019-04-07,12:00:24,631.0,1,2.45,2.45,Beverages,Coffee,Premium brewed coffee,0.49,2018-11-17,1992.0,Younger Millennials
43,2019-04-05,14:21:24,8155.0,1,3.50,3.50,Beverages,Coffee,Gourmet brewed coffee,0.70,2017-01-30,1987.0,Older Millennials
44,2019-04-15,12:09:51,5146.0,1,3.10,3.10,Beverages,Coffee,Premium brewed coffee,0.62,2018-10-17,1996.0,Gen Z
46,2019-04-14,09:30:08,8003.0,1,45.00,45.00,Whole Bean/Teas,Coffee beans,Premium Beans,36.00,2017-01-19,1991.0,Younger Millennials
47,2019-04-02,17:15:04,8082.0,2,5.00,2.50,Beverages,Tea,Brewed Chai tea,0.63,2017-08-17,1981.0,Older Millennials
49,2019-04-12,10:34:31,5820.0,1,4.50,4.50,Food,Bakery,Scone,2.93,2018-03-06,1991.0,Younger Millennials
51,2019-04-03,10:59:41,8033.0,2,6.00,3.00,Beverages,Coffee,Gourmet brewed coffee,0.60,2018-09-16,1994.0,Younger Millennials
52,2019-04-07,07:30:36,3.0,2,6.00,3.00,Beverages,Coffee,Gourmet brewed coffee,0.60,2017-01-10,1950.0,Baby Boomers
53,2019-04-03,15:52:38,664.0,2,5.00,2.50,Beverages,Tea,Brewed Black tea,0.63,2019-01-24,1996.0,Gen Z
59,2019-04-03,15:12:13,727.0,2,4.00,2.00,Beverages,Coffee,Gourmet brewed coffee,0.40,2017-08-13,1964.0,Baby Boomers
60,2019-04-25,08:16:51,777.0,1,3.50,3.50,Food,Bakery,Biscotti,2.28,2018-09-30,1989.0,Older Millennials
61,2019-04-02,18:49:47,162.0,1,3.50,3.50,Beverages,Drinking Chocolate,Hot chocolate,2.63,2018-03-24,1977.0,Gen X
62,2019-04-08,20:20:16,5790.0,1,3.10,3.10,Beverages,Coffee,Premium brewed coffee,0.62,2018-02-12,1975.0,Gen X
64,2019-04-01,14:53:33,5353.0,1,4.75,4.75,Beverages,Drinking Chocolate,Hot chocolate,3.56,2017-07-18,1985.0,Older Millennials
67,2019-04-08,07:18:21,235.0,1,3.00,3.00,Beverages,Tea,Brewed Black tea,0.75,2018-10-11,1990.0,Younger Millennials
70,2019-04-11,09:48:27,100.0,2,8.50,4.25,Beverages,Coffee,Barista Espresso,0.85,2017-10-04,1967.0,Gen X
71,2019-04-05,15:13:52,240.0,1,3.75,3.75,Food,Bakery,Pastry,2.44,2018-10-25,1991.0,Younger Millennials
72,2019-04-27,10:08:48,8394.0,1,2.50,2.50,Beverages,Coffee,Gourmet brewed coffee,0.50,2017-03-31,1991.0,Younger Millennials
73,2019-04-20,11:48:27,8344.0,1,2.00,2.00,Beverages,Coffee,Gourmet brewed coffee,0.40,2018-01-14,1988.0,Older Millennials
75,2019-04-02,12:53:20,734.0,2,7.50,3.75,Beverages,Coffee,Barista Espresso,0.75,2017-10-10,1967.0,Gen X
76,2019-04-19,06:33:12,8206.0,2,5.00,2.50,Beverages,Tea,Brewed Green tea,0.63,2018-02-06,1986.0,Older Millennials
77,2019-04-14,08:02:43,686.0,2,6.00,3.00,Beverages,Tea,Brewed herbal tea,0.75,2019-03-11,1999.0,Gen Z
79,2019-04-05,14:50:51,350.0,2,7.00,3.50,Beverages,Coffee,Organic brewed coffee,0.70,2017-04-15,1956.0,Baby Boomers
80,2019-04-10,17:12:27,546.0,1,3.50,3.50,Food,Bakery,Biscotti,2.28,2018-05-25,1981.0,Older Millennials
82,2019-04-04,18:16:20,548.0,1,2.50,2.50,Beverages,Coffee,Drip coffee,0.50,2018-05-29,1981.0,Older Millennials
83,2019-04-10,13:45:26,8227.0,1,3.75,3.75,Food,Bakery,Pastry,2.44,2019-04-07,1952.0,Baby Boomers
84,2019-04-12,09:36:27,26.0,1,3.75,3.75,Food,Bakery,Pastry,2.44,2017-03-14,1954.0,Baby Boomers
85,2019-04-07,10:49:27,289.0,2,8.00,4.00,Beverages,Tea,Brewed Chai tea,1.00,2019-03-09,1999.0,Gen Z
86,2019-04-04,15:20:06,700.0,2,7.50,3.75,Beverages,Coffee,Barista Espresso,0.75,2019-04-09,2001.0,Gen Z
87,2019-04-03,15:33:20,8126.0,1,2.50,2.50,Beverages,Tea,Brewed Chai tea,0.63,2017-06-04,1960.0,Baby Boomers
89,2019-04-21,10:46:04,8428.0,2,5.00,2.50,Beverages,Tea,Brewed Chai tea,0.63,2019-02-01,1964.0,Baby Boomers
92,2019-04-02,17:31:34,5141.0,1,3.75,3.75,Food,Bakery,Scone,2.44,2018-09-16,1996.0,Gen Z
95,2019-04-09,19:58:13,642.0,1,3.75,3.75,Beverages,Drinking Chocolate,Hot chocolate,2.81,2018-12-10,1993.0,Younger Millennials
97,2019-04-25,16:59:43,5119.0,1,2.65,2.65,Food,Bakery,Scone,2.11,2017-03-31,1982.0,Older Millennials
99,2019-04-22,18:05:59,513.0,1,2.20,2.20,Beverages,Coffee,Organic brewed coffee,0.44,2018-03-18,1977.0,Gen X

In [57]:
unit_mean = df["unit_price"].mean()
unit_mean

np.float64(3.7432999999999996)

In [58]:
def get_locs(product):
    count = 0
    loc = []
    for i in range(len(df)):
        if df["product_group"][i] == product:
            count += 1
            loc.append(i)
    return loc

In [29]:
def get_mean(product):
    loc = get_locs(product=product)
    total = 0
    for i in loc:
        total += df["unit_price"][i]
        mean = total/len(loc)
    return mean

In [59]:
print(f"food average: {get_mean(product="Food")}")
print(f"beverage average: {get_mean(product='Beverages')}")

food average: 3.652
beverage average: 3.1212499999999994

In [62]:
def classify(df):
    classified = {
        "Baby_Boomers": 0,
        "Gen_X": 0,
        "Gen_Z": 0,
        "Older_Millenials": 0,
        "Younger_Millenials": 0
    }
    for i in range(len(df)):
        generation = df["customer_generation"][i]
        
        if generation == "Younger Millennials":
            classified["Younger_Millenials"] += 1
        elif generation == "Older Millennials":
            classified["Older_Millenials"] += 1
        elif generation == "Baby Boomers":
            classified["Baby_Boomers"] += 1
        elif generation == "Gen X":
            classified["Gen_X"] += 1
        elif generation == "Gen Z":
            classified["Gen_Z"] += 1 

    return classified


classified = classify(df=df)
print(classified)

{'Baby_Boomers': 9, 'Gen_X': 8, 'Gen_Z': 11, 'Older_Millenials': 13, 'Younger_Millenials': 11}

In [63]:
total = 0
for generation in classified:
    total += classified[generation]
gen_z = classified["Gen_Z"]

print((gen_z/total)*100)

21.153846153846153